src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403, handler400
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('account/', include('user_account.urls'), name='account'),
    path('testset/', include('testset.urls'), name='testset'),
]

urlpatterns +=   \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


handler400 = 'core.views.handler400'
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'
handler403 = 'core.views.handler403'

src/testset/urls.py
from django.urls import path

from . import views

app_name = 'testset'

urlpatterns = [
    path('list', views.TestListView.as_view(), name='list'),
    path('<int:pk>/next', views.TestRunView.as_view(), name='next'),
    path('start/<int:test_pk>', views.TestStartView.as_view(), name='start'),
    path('leader', views.UserLeaderBoardListView.as_view(), name='leader_bord'),
]

src/user_account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('register', views.CreateUserAccountView.as_view(), name='registration'),
    path('login', views.UserAccountLoginView.as_view(), name='login'),
    path('logout', views.UserAccountLogoutView.as_view(), name='logout'),
    path('profile', views.UserAccountProfileView.as_view(), name='profile'),
    path('contact_us', views.ContactUsView.as_view(), name='contact_us'),

]

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>{% block title %} {{title}} {% endblock %}</title>
</head>
<body>

<div class="container">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'index' %}">TESTS <span class="sr-only">(current)</span></a>
<!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"-->
<!--                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'testset:list' %}"><b>Test suites</b></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'testset:leader_bord' %}"><b>Leader Bord</b></a>
                </li>

            </ul>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item {% if request.path == profile_url %} active {%endif%}">
                            <a class="nav-link" href="{% url 'account:contact_us' %}">Contact us</a>
                     </li>
                    <li class="nav-item">
                        <img class="rounded-circle p-1 m-1" width="45" height="45"  src="{{ user.image.url }}">
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'account:profile' %}">Profile ({{user.username}})</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'account:registration' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
<!--            <form class="form-inline my-2 my-lg-0">-->
<!--                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--            </form>-->
        </div>
    </nav>

    <div class="p-2">
        {% include 'includes/messages.html' %}
    </div>
    <h2 class="p-3 m-1 bg-light rounded text-center">
        {% block title_page %}{{ title }}{% endblock %}
    </h2>
    <div class="border border-dark rounded p-3 m-3">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>Welcome to TestSet!</h1>
{% endblock %}